# Site Settings
title: Joshua Bloom | Portfolio
email: joshbloom@gmail.com
description: General background, work, presentations, bio, etc
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-78470181-1"

# User Settings
username: Joshua Bloom
#user_description: Some text about you.
#disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: code128
#twitter_username: joshbloom
linkedin_username: jbloom
instagram_username: joshbloom

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Welcome
    url: /
  - title: Work
    url: /work/
  - title: Presentations
    url: /presentations/
  - title: Contact
    url: /contact/
    
  # - title: Resume
  #   url: /assets/Joshua_Bloom_Resume_2018_sm.pdf

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
